server:
  port: 8084
  response:
    headers:
      allow: GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS

spring:
  application:
    name: pay

  mvc:
    dispatch-options-request: true

  datasource:
    url: jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL #jdbc:postgresql://localhost:5433/postgres_db_payments_notification
    driver-class-name: org.h2.Driver #org.postgresql.Driver
    username: sa #admin
    password: "" #${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect #org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: never

  kafka:
    bootstrap:
      servers: localhost:9092

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 86400000