server:
  port: 8084

spring:
  application:
    name: pay

  mvc:
    dispatch-options-request: true

  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    hikari:
      minimum-pool-size: 10
      maximum-pool-size: 10
      connection-timeout: 20000
      idle-timeout: 3000
    username: ${MYSQL_USER}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
      cache:
        use_second_level_cache: false
      jdbc:
        fetch_size: 100

  sql:
    init:
      mode: always
      platform: mysql

  kafka:
    bootstrap:
      servers: localhost:${KAFKA_PORT}
    properties:
      spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 86400000

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    com.danilodps.pay: DEBUG
#    org.springframework.security: DEBUG
#    com.zaxxer.hikari: DEBUG
#    com.zaxxer.hikari.HikariConfig: DEBUG